title:              Craft Trade
email:              your-email@example.com
description:        Современное приложение для создания торговых ботов на крипторынке
author:             Craft Trade Company
baseurl:
url:                "https://craft-trade-bot.online"

telegram_bot:       "craft_trade_bot?start=official"
telegram_channel:   "+NL0KuVkfenE2Yzcy"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
